apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: kiali-operator
spec:
  auth:
    #strategy: anonymous
    strategy: openid
    openid:
      client_id: kiali
      client_secret: ${KIALI_CLIENT_SECRET}
      api_token: access_token # access_token | id_token
      issuer_uri: https://dex.kdvops.com
      scopes:
        - openid
        - profile
        - email
        - groups
      username_claim: preferred_username

  server:
    web_root: /kiali
    base_path: /kiali
    web_fqdn: https://kiali.kdvops.com
    web_scheme: https
    #require_auth: true
    cookies:
      same_site: None
      secure: true
      
  deployment:
    #envFrom:
    #  - secretRef:
    #      name: kiali-oidc-secret
      
    accessible_namespaces:
      - "**"

  external_services:
    prometheus:
      url: http://prometheus-server.monitoring:80

    grafana:
      enabled: true
      internal_url: http://grafana.monitoring:80
      auth:
        type: none
