apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: kiali-operator
spec:
  auth:
    strategy: anonymous
    #strategy: openid
    #openid:
    #  client_id: kiali
    #  client_secret: "super-strong-secret" # | ${KIALI_CLIENT_SECRET} 
    #  api_token: access_token # access_token | id_token
    #  issuer_uri: https://dex.kdvops.com
    #  scopes:
    #    - openid
    #    - profile
    #    - email
    #    - groups
    #  username_claim: preferred_username

  server:
    web_root: /kiali
    web_fqdn: https://kiali.kdvops.com
    #require_auth: true
    #web_scheme: https  # no reconoce
    #base_path: /kiali  # no reconoce
    #cookies:
    #  same_site: None
    #  secure: true
      
  deployment:
    cluster_wide_access: true
    #envFrom:
    #  - secretRef:
    #      name: kiali-secret
    #envFrom:
    #  - secretRef:
    #      name: kiali-oidc-secret
      
    accessible_namespaces:
      - "**"

  external_services:
    prometheus:
      url: http://prometheus-server.monitoring:80

    grafana:
      enabled: true
      internal_url: http://grafana.monitoring:80
      auth:
        type: none
