apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali
  namespace: argocd
  annotations:
    argocd.argoproj.io/ignore-health-checks: |
      kiali.io/Kiali
spec:
  project: default

  sources:
    - repoURL: https://kiali.org/helm-charts
      chart: kiali-operator
      targetRevision: "*"
      helm:
        releaseName: kiali-operator
        values: |
          cr:
            create: false
                  
    - repoURL: https://github.com/kdvops/ArgoCD.git
      targetRevision: HEAD
      path: Application/kiali/chield/manifests
  
  destination:
    server: https://kubernetes.default.svc
    namespace: kiali-operator

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
