apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: dex
  namespace: dex
spec:
  hosts:
  - dex.tu-dominio.com
  gateways:
  - istio-system/main-gateway
  http:
  - route:
    - destination:
        host: dex.dex.svc.cluster.local
        port:
          number: 5556
