apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dex
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://charts.dexidp.io
    chart: dex
    targetRevision: "*"
    helm:
      #valueFiles:
      #  - values.yaml
      
      values: |
        env:
        - name: AZURE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: dex-azure-secrets
              key: AZURE_CLIENT_ID
        - name: AZURE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: dex-azure-secrets
              key: AZURE_CLIENT_SECRET
        - name: AZURE_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: dex-azure-secrets
              key: AZURE_TENANT_ID

        config:
          issuer: https://dex.kdvops.com

          storage:
            type: kubernetes
            config:
              inCluster: true

          web:
            http: 0.0.0.0:5556

          connectors:
          - type: microsoft
            id: azure
            name: Azure Entra ID
            config:
              clientID: ${AZURE_CLIENT_ID}
              clientSecret: ${AZURE_CLIENT_SECRET}
              tenant: ${AZURE_TENANT_ID}
              redirectURI: https://dex.kdvops.com/callback

  destination:
    server: https://kubernetes.default.svc
    namespace: dex

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
